### ISSUE TITLE
Chart repo KO

### ISSUE THREAD

**Issue by felixPG** [kubernetes-helm/monocular#367]
Hi:

I have 2 problems, maybe the first is a bug:

1. When I create a repository with name http://bla.blabla **I CANT REMOVE THE REPOSITORY**, when is created with a common name like myrepo, etc, the delete work fine.

2. I have added the official chart repo and is working fine. 
Custom repo: 
Nginx serving a helm repository, index.yaml are accesible without problems and tar.gz files are accesible and I can download the files with a normal browser, BUT, monocular **CANT SEE nothing inside my repository**.
The chart repository structure is as simple as:

charts/
  |
  |- index.yaml
  |
  |- alpine-0.1.2.tgz

Please, can anybody say me or give me a link to create a helm repository that I could see in monocular???

**Comment by prydonius** [comment]
Hi @felixPG,

The first one does sound like a bug, I'll take a look. For the second, what is the cache refresh interval (https://github.com/kubernetes-helm/monocular/blob/master/deployment/monocular/values.yaml#L48) set to? By default, you will need to wait up to an hour for Monocular to fetch content from your repo.

**Comment by felixPG** [comment]
OMG??, please, could you update your documentation at https://github.com/kubernetes/helm/blob/master/docs/chart_repository.md and make a note in **BOLD** with this???

Almost crazy making a repo like with helm serve --address X.X.X..X:5432 --repo-path /opt/charts and repo does not show nothing in UI.

Why 1 hour???, Do you thik @prydonius that less time affect the performance of the API server?, 5 minutes are OK??

**Comment by felixPG** [comment]
Is possible @prydonius  that you could include in a PR the possibility to update an existing repo?? Now only is possible add and delete, **NOT UPDATE**

Regards

**Comment by prydonius** [comment]
@felixPG 1 hour is just what we are using, but you could set it to anything. It doesn't really affect the performance of the server, but note that Monocular will request the index.yaml at that interval from your repository server.

This is definitely something we plan to change, for one the repo should update as soon as it is added, however before we are able to make these changes there are some structural changes that need to be made.

**Comment by felixPG** [comment]
thanks so much @prydonius . Only change the interval to less values only for test purpose. In my case is not necesary less time once I have the repo running with all the necesary apps.

**Comment by felixPG** [comment]
@prydonius is not working changing to 1 minute the cache refresh interval, also:

1. I added manually to helm de test repo

```  
root@s-smartc2-zprei:/opt/kubernetes/nfs-deploy/postgres/charts# helm repo list
NAME            URL
stable          https://kubernetes-charts.storage.googleapis.com/
monocular       https://kubernetes-helm.github.io/monocular
test            http://192.168.133.2:5432/charts
```

2. Find a chart that I have in my test repo in all helm repo:

```
root@s-smartc2-zprei:/opt/kubernetes/nfs-deploy/postgres/charts# helm search monocular
NAME                    VERSION DESCRIPTION
monocular/monocular     0.4.9   Monocular is a search and discovery front end f...
**test/monocular          0.4.9   Monocular is a search and discovery front end** f...
root@s-smartc2-zprei:/opt/kubernetes/nfs-deploy/postgres/charts#
```
As you can see the monocular chart appear in the official repo and in test repo, ALL OK.

3. Monocular API does not find anything in my repo test, in the API logs:
```
2017/10/02 08:37:40 data.Charts AllFromRepo(test) error (no charts found for repo test
```
Why helm find charts inside my repo and monocular NOT?, is not my repo is monocular????

**Comment by prydonius** [comment]
@felixPG do you have logs from the refresh?

**Comment by felixPG** [comment]
Did you man cache refresh?

**Comment by prydonius** [comment]
Yes, you should see a log message describing the chart and repo during the cache refresh.

**Comment by felixPG** [comment]
Ok, here the logs:

``` 
time="2017-10-02T08:47:35Z" level=info msg="Local cache missing" name=monocular version=0.4.9
time="2017-10-02T08:47:35Z" level=info msg="Downloading metadata" dest="/monocular/repo-data/test/monocular/0.4.9/chart.tgz" source=monocular-0.4.9.tgz
time="2017-10-02T08:47:35Z" level=error msg="Error on DownloadAndExtractChartTarball" error="Get monocular-0.4.9.tgz: unsupported protocol scheme """

**Comment by prydonius** [comment]
@felixPG looks like your `index.yaml` is malformed, did you pass the correct `--url` flag to `helm repo index`?

**Comment by felixPG** [comment]
Ok, the whole work:

1. Build the index
``` 
helm repo index /opt/kubernetes/nfs-deploy/postgres/charts
```
2. Index.yaml content:
``` 
apiVersion: v1
entries:
  monocular:
  - apiVersion: v1
    appVersion: v0.4.0
    created: 2017-10-02T11:13:35.472235351+02:00
    description: Monocular is a search and discovery front end for Helm Charts Repositories.
    digest: 30ff809a365191799a211f1efdbd06f1e21dd088ccc87dbdfdf1e50d365f50b3
    home: https://github.com/kubernetes-helm/monocular
    maintainers:
    - email: adnan@bitnami.com
      name: prydonius
    name: monocular
    sources:
    - https://github.com/kubernetes-helm/monocular
    urls:
    - monocular-0.4.9.tgz
    version: 0.4.9
generated: 2017-10-02T11:13:35.471380584+02:00
```
3. Add repo to helm
``` 
helm repo add test http://192.168.133.2:5432/charts
"test" has been added to your repositories
```
4. Test repo
```
root@s-smartc2-zprei:/opt/kubernetes/nfs-deploy/postgres/charts# helm search monocular
NAME                    VERSION DESCRIPTION
monocular/monocular     0.4.9   Monocular is a search and discovery front end f...
test/monocular          0.4.9   Monocular is a search and discovery front end f...
root@s-smartc2-zprei:/opt/kubernetes/nfs-deploy/postgres/charts#
```

5. API LOGS:
```
time="2017-10-02T09:17:37Z" level=info msg="Using cache directory" path="/monocular/repo-data"
time="2017-10-02T09:17:37Z" level=info msg="Local cache missing" name=monocular version=0.4.9
time="2017-10-02T09:17:37Z" level=info msg="Downloading metadata" dest="/monocular/repo-data/test/monocular/0.4.9/chart.tgz" source=monocular-0.4.9.tgz
time="2017-10-02T09:17:37Z" level=error msg="Error on DownloadAndExtractChartTarball" error="Get monocular-0.4.9.tgz: unsupported protocol scheme """

```

So, helm add the repo succesfully, the problem is with MONOCULAR!

**Comment by prydonius** [comment]
The issue is that the URLs in your index are not a real URL:

```
apiVersion: v1
entries:
  monocular:
...
    urls:
    - monocular-0.4.9.tgz
...
```
