### ISSUE TITLE
Questions for docker-compose

### ISSUE THREAD

**Issue by hiscal2015** [kubernetes-helm/monocular#410]
Hi, 

I'm trying to deploy monocular with docker-compose today, but have some questions need help.

For api:
```
  api:
    tty: true
    build: ./dev_env/api
    volumes:
      - ./src/api:/go/src/github.com/kubernetes-helm/monocular/src/api
      # Config example file
      - ./docs/config.example.yaml:/root/monocular/config/monocular.yaml
      # Used for loading kubernetes context used on Helm releases integration
      - $HOME/.kube/:/root/.kube
    environment:
      - ENVIRONMENT=development
```
Questions:
1) There's a redis config in config.example.yaml, is it necessary?
2) What's the ENVIRONMENT here? Means kubeconfig current context?

For UI:
```
  ui:
    tty: true # Enables debugging capabilities when attached to this container.
    build: ./dev_env/ui
    ports:
      - 4200:4200
    volumes:
      - ./src/ui:/app
    command: "ng serve --host 0.0.0.0 --proxy-config proxy.conf.json"
```
Questions:
1) docker run -d -v /monocular/src/ui:/app -p 4200:4200 --name monocular-ui bitnami/monocular-ui "ng serve --host 0.0.0.0 --proxy-config /app/proxy.conf.json"
```
Welcome to the Bitnami nginx container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-nginx
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-nginx/issues
Send us your feedback at containers@bitnami.com

[FATAL tini (9)] exec ng serve --host 0.0.0.0 --proxy-config /app/proxy.conf.json failed: No such file or directory
```
Why it is reporting there's no proxy.conf.json? It should be there:
```
root@server:/monocular/src/ui# ll
total 560
drwxr-xr-x 5 root root   4096 Dec 21 13:15 ./
drwxr-xr-x 4 root root   4096 Dec 21 13:15 ../
-rw-r--r-- 1 root root   1236 Dec 21 13:15 .angular-cli.json
-rw-r--r-- 1 root root    245 Dec 21 13:15 .editorconfig
-rw-r--r-- 1 root root    516 Dec 21 13:15 .gitignore
-rw-r--r-- 1 root root    392 Dec 21 13:15 Makefile
-rw-r--r-- 1 root root   1763 Dec 21 13:15 README.md
drwxr-xr-x 2 root root   4096 Dec 21 13:15 e2e/
-rw-r--r-- 1 root root   1088 Dec 21 13:15 karma.conf.js
-rw-r--r-- 1 root root 299893 Dec 21 13:15 package-lock.json
-rw-r--r-- 1 root root   2236 Dec 21 13:15 package.json
-rw-r--r-- 1 root root    722 Dec 21 13:15 protractor.conf.js
-rw-r--r-- 1 root root    119 Dec 21 13:15 proxy.conf.json
drwxr-xr-x 2 root root   4096 Dec 21 13:15 rootfs/
drwxr-xr-x 5 root root   4096 Dec 21 13:15 src/
-rw-r--r-- 1 root root    363 Dec 21 13:15 tsconfig.json
-rw-r--r-- 1 root root   3040 Dec 21 13:15 tslint.json
-rw-r--r-- 1 root root 195945 Dec 21 13:15 yarn.lock

```
2) If above issue fixed, then look at proxy.conf.json, does it mean /app will proxy to api container by port 3000 (default setting)? So do I have to change to the correct port (api port should be 8081)?
```
{
  "/api": {
    "target": "http://api:3000",
    "secure": false,
    "pathRewrite": {
      "^/api": ""
    }
  }
}
```
