### ISSUE TITLE
Invalid content type for assets

### ISSUE THREAD

**Issue by timurkhafizov** [kubernetes-helm/monocular#426]
On fresh installation of `monocular` we encounter issue where content type for assets is wrong.

Here are request headers:
```
Host: monocular.domain.internal
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0
Accept: text/css,*/*;q=0.1
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://monocular.domain.internal/
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
```

and response headers:
```
Content-Encoding: gzip
Content-Type: text/html
Date: Thu, 08 Mar 2018 11:42:33 GMT
Etag: W/"5a16a168-1180"
Last-Modified: Thu, 23 Nov 2017 10:22:32 GMT
Server: nginx/1.12.2
Vary: Accept-Encoding
X-Frame-Options: SAMEORIGIN
Content-Length: 2026
Connection: keep-alive
```

Some input data:

  0. Fresh installation with `helm`: `helm upgrade --install monocular monocular/monocular --namespace kube-system -f monocular/values.yml`
  1. Traefik v1.5.3 as Ingress class
  2. `helm` values file:
```
api:
  replicaCount: 1

  image:
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 10m
      memory: 64Mi

  config:
    repos:
      - name: savedo
        url: https://chartmuseum.domain.internal
        source: https://github.com/chart/sources
    # Enable Helm deployment integration
    releasesEnabled: false
ui:
  replicaCount: 1
  image:
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 10m
      memory: 64Mi

  googleAnalyticsId:

prerender:
  image:
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 10m
      memory: 64Mi

ingress:
  enabled: true

  hosts:
  - monocular.domain.internal

  annotations:
    # Traefik ingress controller
    traefik.frontend.rule.type: "PathPrefixStrip"
    kubernetes.io/ingress.class: "traefik"
```

I've also tried to downgrade `monocular` to v1.5.4 but I see the same issue.
There must be something I miss.

Any ideas are appreciated!
