### ISSUE TITLE
Monocular api download repo even repo is not configured.

### ISSUE THREAD

**Issue by YunSangJun** [kubernetes-helm/monocular#443]
I commented out repo setting on values.yaml because it takes too long to synchronize repo.
```
api:
  ...
  config:
    repos:
      # Official repositories
      #- name: stable
      #  url: https://kubernetes-charts.storage.googleapis.com
      #  source: https://github.com/kubernetes/charts/tree/master/stable
      #- name: incubator
      #  url: https://kubernetes-charts-incubator.storage.googleapis.com
      #  source: https://github.com/kubernetes/charts/tree/master/incubator
      # Add your own repository
  ...
```

But it looks like that Monocular api pod is downloading repo. 
Is it working properly?.
```
$ kubectl get pods -n monocular
NAME                                            READY     STATUS             RESTARTS   AGE
monocular-mongodb-779c69c4b8-ldd8w              1/1       Running            0          41m
monocular-monocular-api-5566949b68-62p4r        0/1       CrashLoopBackOff   3          9m
monocular-monocular-prerender-cdc9449bf-bvf4f   1/1       Running            0          41m
monocular-monocular-ui-59948df86d-hphcw         1/1       Running            0          9m
```
```
$ kubectl logs -f monocular-monocular-api-5d894ff7d6-9d4j6 -n monocular
time="2018-05-02T08:15:13Z" level=info msg="Configuration bootstrap init" configFile="/monocular/config/monocular.yaml" 
time="2018-05-02T08:15:13Z" level=info msg="Configuration file found!" 
time="2018-05-02T08:15:13Z" level=info msg="Loading CORS from config file" 
time="2018-05-02T08:15:13Z" level=info msg="Loading repositories from config file" 
time="2018-05-02T08:15:13Z" level=info msg="Configuration bootstrap finished" 
time="2018-05-02T08:15:13Z" level=info msg="Using cache directory" path="/monocular/repo-data" 
time="2018-05-02T08:16:22Z" level=info msg="Deprecated chart skipped" name=stash 
time="2018-05-02T08:16:22Z" level=info msg="Deprecated chart skipped" name=aws-cluster-autoscaler 
time="2018-05-02T08:16:22Z" level=info msg="Deprecated chart skipped" name=kubedb 
time="2018-05-02T08:16:23Z" level=info msg="Deprecated chart skipped" name=gitlab-ce 
time="2018-05-02T08:16:23Z" level=info msg="Deprecated chart skipped" name=swift 
time="2018-05-02T08:16:23Z" level=info msg="Deprecated chart skipped" name=voyager 
time="2018-05-02T08:16:23Z" level=info msg="Deprecated chart skipped" name=kube-lego 
time="2018-05-02T08:16:23Z" level=info msg="Deprecated chart skipped" name=dask-distributed 
time="2018-05-02T08:16:23Z" level=info msg="Deprecated chart skipped" name=telegraf 
time="2018-05-02T08:16:23Z" level=info msg="Deprecated chart skipped" name=nginx-lego 
time="2018-05-02T08:16:23Z" level=info msg="Deprecated chart skipped" name=searchlight 
time="2018-05-02T08:16:23Z" level=info msg="Deprecated chart skipped" name=sugarcrm 
time="2018-05-02T08:16:23Z" level=info msg="Deprecated chart skipped" name=gitlab-ee 
time="2018-05-02T08:16:23Z" level=info msg="Deprecated chart skipped" name=g2 
time="2018-05-02T08:16:23Z" level=info msg="Deprecated chart skipped" name=kubed 
time="2018-05-02T08:16:23Z" level=info msg="Local cache missing" name=mongodb-replicaset version=2.1.3 
time="2018-05-02T08:16:23Z" level=info msg="Downloading metadata" dest="/monocular/repo-data/stable/mongodb-replicaset/2.1.3/chart.tgz" source="https://kubernetes-charts.storage.googleapis.com/mongodb-replicaset-2.1.3.tgz" 
time="2018-05-02T08:16:23Z" level=info msg="Local cache missing" name=openebs version=0.5.3 
time="2018-05-02T08:16:23Z" level=info msg="Downloading metadata" dest="/monocular/repo-data/stable/openebs/0.5.3/chart.tgz" source="https://kubernetes-charts.storage.googleapis.com/openebs-0.5.3.tgz" 
time="2018-05-02T08:16:23Z" level=info msg="Local cache missing" name=mongodb version=2.0.2 
time="2018-05-02T08:16:23Z" level=info msg="Downloading metadata" dest="/monocular/repo-data/stable/mongodb/2.0.2/chart.tgz" source="https://kubernetes-charts.storage.googleapis.com/mongodb-2.0.2.tgz"
```
