### ISSUE TITLE
appVersion from Chart.yaml is not used in templates

### ISSUE THREAD

**Issue by vhurtevent** [kubernetes-helm/monocular#464]
Got charts and templates using .Chart.appVersion to specify one time the application version and use it to build image repository/tag, labels, custom ingress hosts, etc.

When using helm client, it works well.

Using chartmuseum to store charts and monocular to deploy applications. Charts are well sync'ed and monocular displays the right appVersion in its UI.

When requesting a deployment, the resulting release has an empty appVersion value, resulting in errors as the image repository/tag, and labels are wrong.

I can't figure out where in the code, the value could be ignored or rewritten.

Source Chart.yaml 
```
apiVersion: v1
name: XXXXXXXX
version: 0.0.1-1
appVersion: 0.0.1-SNAPSHOT
kubeVersion: >1
tillerVersion: ">2.0.0"
description: XXXXX
```

Resulting labels in resource manifest, using monocular 
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-06-05T09:48:27Z
  generation: 1
  labels:
    app: XXXXXXXX
    appVersion: ""
    chart: XXXXXXXX-0.0.1-1
    component: frontend
    date: 2018-06-05
    heritage: Tiller
```
